"""Taglines, faction data, and flavor text for the Chessticon codex."""

# ── Faction mappings ──────────────────────────────────────────────────

PIECE_FACTIONS = {
    # Classic (6)
    "pawn": "Classic", "knight": "Classic", "bishop": "Classic",
    "rook": "Classic", "queen": "Classic", "king": "Classic",
    # Undead (5)
    "ghost": "Undead", "reaper": "Undead", "poltergeist": "Undead",
    "parasite": "Undead", "void": "Undead",
    # Beast (5)
    "wyvern": "Beast", "imp": "Beast", "king_rat": "Beast",
    "mimic": "Beast", "phoenix": "Beast",
    # Warrior (6)
    "berserker_piece": "Warrior", "duelist": "Warrior", "lancer": "Warrior",
    "charger": "Warrior", "assassin": "Warrior", "sentinel": "Warrior",
    # Magic (7)
    "witch": "Magic", "healer": "Magic", "bard": "Magic",
    "alchemist_piece": "Magic", "summoner": "Magic", "trickster": "Magic",
    "time_mage": "Magic",
    # Mechanical (6)
    "cannon": "Mechanical", "bomb": "Mechanical", "totem": "Mechanical",
    "decoy": "Mechanical", "wall": "Mechanical", "golem": "Mechanical",
    # Special (5)
    "gambler": "Special", "anchor_piece": "Special",
    "mirror_piece": "Special", "shapeshifter": "Special", "leech": "Special",
}

FACTION_ORDER = ["Classic", "Undead", "Beast", "Warrior", "Magic", "Mechanical", "Special"]

FACTION_ICONS = {
    "Classic": "\u265A",   # ♚
    "Undead": "\u2620",    # ☠
    "Beast": "\u2682",     # ⚂ (claw-like)
    "Warrior": "\u2694",   # ⚔
    "Magic": "\u2605",     # ★
    "Mechanical": "\u2699", # ⚙
    "Special": "\u2666",   # ♦
}

# ── Taglines ──────────────────────────────────────────────────────────
# Namespaced: "piece:key", "piece_mod:key", "cell_mod:key", etc.

TAGLINES = {
    # ── Pieces ────────────────────────────────────────────────────────
    # Classic
    "piece:pawn": "Cannon fodder with ambition.",
    "piece:knight": "The L-shaped menace.",
    "piece:bishop": "Diagonally inclined.",
    "piece:rook": "Straight to the point.",
    "piece:queen": "Slays in every direction.",
    "piece:king": "Long live the king. Hopefully.",
    # Undead
    "piece:ghost": "You can't kill what's already dead.",
    "piece:reaper": "Harvest season never ends.",
    "piece:poltergeist": "It moves your furniture. And your pieces.",
    "piece:parasite": "Latches on. Never lets go.",
    "piece:void": "Stare into the abyss. It stares back.",
    # Beast
    "piece:wyvern": "Not a dragon. Don't ask.",
    "piece:imp": "Small, annoying, surprisingly lethal.",
    "piece:king_rat": "Swarm royalty.",
    "piece:mimic": "Is that a treasure chest or\u2014 oh no.",
    "piece:phoenix": "Death is merely an inconvenience.",
    # Warrior
    "piece:berserker_piece": "Anger management? Never heard of it.",
    "piece:duelist": "En garde, you filthy casual.",
    "piece:lancer": "First in. Pointy end forward.",
    "piece:charger": "No brakes. No regrets.",
    "piece:assassin": "Nothing personal, kid.",
    "piece:sentinel": "You shall not pass. Literally.",
    # Magic
    "piece:witch": "Double, double, toil and trouble.",
    "piece:healer": "I didn't go to med school for this.",
    "piece:bard": "Anyway, here's Wonderwall.",
    "piece:alchemist_piece": "Equivalent exchange, more or less.",
    "piece:summoner": "Why fight when others can?",
    "piece:trickster": "Now you see me. Now you don't.",
    "piece:time_mage": "I've seen how this ends. Twice.",
    # Mechanical
    "piece:cannon": "Point. Click. Boom.",
    "piece:bomb": "Handle with extreme care.",
    "piece:totem": "Buffs the squad. Dies for the cause.",
    "piece:decoy": "Look over here! No, over HERE!",
    "piece:wall": "404: Path not found.",
    "piece:golem": "Built different. Built tough.",
    # Special
    "piece:gambler": "All in. Every. Single. Time.",
    "piece:anchor_piece": "Not going anywhere. Neither are you.",
    "piece:mirror_piece": "Imitation is the sincerest form of flattery.",
    "piece:shapeshifter": "Identity crisis as a combat strategy.",
    "piece:leech": "Sharing is caring. Your HP is now mine.",

    # ── Piece Modifiers ───────────────────────────────────────────────
    "piece_mod:flaming": "Everything's better with fire.",
    "piece_mod:armored": "Thick skin, thicker skull.",
    "piece_mod:swift": "Gotta go fast.",
    "piece_mod:piercing": "Goes right through you.",
    "piece_mod:royal": "Bow before the bling.",
    "piece_mod:vampiric": "Dinner is served.",
    "piece_mod:explosive": "Going out with a bang.",
    "piece_mod:frozen": "Cool it. Literally.",
    "piece_mod:toxic": "Tastes like purple.",
    "piece_mod:ethereal": "Phase through your problems.",
    "piece_mod:thorned": "Hug me. I dare you.",
    "piece_mod:lucky": "Feeling lucky, punk?",
    "piece_mod:magnetic": "Get over here!",
    "piece_mod:splitting": "Cut one down, two more shall take its place.",
    "piece_mod:reflective": "I'm rubber, you're glue.",
    "piece_mod:gilded": "Cha-ching on every kill.",
    "piece_mod:titan": "Bigger. Stronger. Slower.",
    "piece_mod:unstable": "Power at a price.",
    "piece_mod:haunted": "Death is only the beginning.",
    "piece_mod:blazing": "Leave nothing but ashes.",

    # ── Cell Modifiers ────────────────────────────────────────────────
    "cell_mod:rage": "Stand here. Hit harder. Simple.",
    "cell_mod:shield": "A safe space. For once.",
    "cell_mod:haste": "Zoom zoom.",
    "cell_mod:phase": "Here one turn, gone the next.",
    "cell_mod:inferno": "The floor is lava. Unironically.",
    "cell_mod:sanctuary": "Even wars have churches.",
    "cell_mod:quicksand": "Slow and steady loses the race.",
    "cell_mod:vortex": "Teleportation: not as fun as it sounds.",
    "cell_mod:gold_mine": "Ka-ching! Stand here, get paid.",
    "cell_mod:mirror_cell": "Reflect on your life choices.",
    "cell_mod:curse": "Bad vibes only.",
    "cell_mod:amplifier": "Turn it up to eleven.",
    "cell_mod:ice": "Watch your step.",
    "cell_mod:volcano": "Erupts on schedule.",
    "cell_mod:beacon": "A light in the darkness.",
    "cell_mod:graveyard": "The dead don't rest here.",

    # ── Border Modifiers ──────────────────────────────────────────────
    "border_mod:fortified": "Built like a castle wall.",
    "border_mod:thorns": "Cross at your own risk.",
    "border_mod:anchor": "Nobody's going anywhere.",
    "border_mod:firewall": "Unauthorized access denied.",
    "border_mod:mirror_border": "Everything bounces back.",
    "border_mod:gravity_well": "Resistance is futile.",
    "border_mod:healing_aura": "Cross here, feel better.",
    "border_mod:speed_gate": "Warp speed, Mr. Sulu.",
    "border_mod:death_zone": "Abandon all hope ye who enter.",
    "border_mod:swap_gate": "Now you're over there.",
    "border_mod:tax_border": "Nothing is certain except this.",

    # ── Tarots ────────────────────────────────────────────────────────
    "tarot:the_flame": "Light it up.",
    "tarot:the_fortress": "Walls within walls.",
    "tarot:the_phantom": "They'll never see it coming.",
    "tarot:the_tide": "The tide waits for no piece.",
    "tarot:the_merchant": "Everything has a price.",
    "tarot:the_necromancer": "What is dead may never die.",
    "tarot:the_jester": "Chaos is a ladder.",
    "tarot:the_tactician": "Outplayed. Outmaneuvered.",
    "tarot:the_mirror": "Look into yourself.",
    "tarot:the_pawn": "Humble beginnings, grand endings.",
    "tarot:the_executioner": "Off with their head.",
    "tarot:the_shepherd": "Tend your flock.",
    "tarot:the_inferno": "Burn it all down.",
    "tarot:the_glacier": "Patience is a weapon.",
    "tarot:the_plague": "Spread the love. The toxic kind.",
    "tarot:the_architect": "Form follows function.",
    "tarot:the_vampire": "Your blood is my potion.",
    "tarot:the_titan": "Bigger isn't always better. Except now.",
    "tarot:the_swarm": "Strength in numbers.",
    "tarot:the_saboteur": "Oops. Was that yours?",
    "tarot:the_gambit": "Risk everything. Gain everything.",
    "tarot:the_hourglass": "Time is on your side. Maybe.",
    "tarot:the_chaos": "Roll the dice. Hope for the best.",
    "tarot:the_sacrifice_tarot": "One must fall for others to rise.",
    "tarot:the_crown": "Heavy is the head.",
    "tarot:the_echo": "History repeats itself.",
    "tarot:the_web": "Tangled alliances.",

    # ── Artifacts ─────────────────────────────────────────────────────
    "artifact:gold_tooth": "Every smile is payday.",
    "artifact:war_drum": "The beat drops. So do enemies.",
    "artifact:iron_crown": "Uneasy lies the head that wears it.",
    "artifact:lucky_coin": "Heads I win, tails you lose.",
    "artifact:blood_pact": "Signed in crimson.",
    "artifact:mirror_shard": "Seven years of bad luck. For them.",
    "artifact:chaos_orb": "Spin the wheel of misfortune.",
    "artifact:anchor_chain": "Grounded in more ways than one.",
    "artifact:whetstone": "A sharp blade, a sharp mind.",
    "artifact:forge_hammer": "Reforged and ready.",
    "artifact:pandemonium": "All hell, pocket-sized.",
    "artifact:necrotome": "Required reading for necromancers.",
    "artifact:heretics_tome": "Forbidden knowledge, forbidden power.",
    "artifact:crown_jewel": "The crown's crown jewel.",
    "artifact:ember_stone": "Warm to the touch. Scorching to enemies.",
    "artifact:frost_shard": "Winter is coming. For real.",
    "artifact:venom_gland": "Extracted from something you don't want to meet.",
    "artifact:scouts_map": "X marks every spot.",
    "artifact:training_dummy": "It takes the hits so you don't.",
    "artifact:loaded_dice": "House always wins.",
    "artifact:battle_standard": "Rally to the flag!",
    "artifact:salvage_kit": "One man's trash, another's treasure.",
    "artifact:tempo_ring": "Time bends to the wearer.",
    "artifact:soul_jar": "Souls sold separately.",
    "artifact:chain_mail": "Links of protection.",
    "artifact:berserkers_torc": "Rage, contained. Barely.",
    "artifact:phase_cloak": "Now you see me...",
    "artifact:plague_doctor": "The cure is worse than the disease.",
    "artifact:trophy_rack": "Proof of past victories.",
    "artifact:resonance_crystal": "Vibrates at the frequency of destruction.",
    "artifact:echo_chamber": "Repeat after me.",
    "artifact:blood_altar": "Sacrifice brings power.",
    "artifact:doomsday_clock": "Tick. Tock.",
    "artifact:philosophers_stone": "Turning lead into gold since forever.",
    "artifact:pandoras_box": "Don't open it. You'll open it.",
    "artifact:grimoire": "Spells for days.",
    "artifact:arsenal": "More dakka.",
    "artifact:generals_baton": "Command and conquer.",
    "artifact:infinity_loop": "What goes around comes around.",
    "artifact:dragons_hoard": "Mine. All mine.",
    "artifact:chaos_engine": "Entropy made manifest.",

    # ── Synergies ─────────────────────────────────────────────────────
    "synergy:minefield": "Step carefully.",
    "synergy:identity_theft": "We have your identity on file.",
    "synergy:necromancer": "They keep coming back.",
    "synergy:rat_king": "Rats. Why did it have to be rats?",
    "synergy:haunted_board": "This board is haunted.",
    "synergy:sacrifice": "Greater good. Greater damage.",
    "synergy:swarm_intelligence": "The hive mind awakens.",
    "synergy:infinite_recursion": "It's turtles all the way down.",
    "synergy:life_drain": "Your health is my health.",
    "synergy:glass_cannon": "Fragile? Yes. Devastating? Also yes.",
    "synergy:firestorm": "We didn't start the fire. Actually, we did.",
    "synergy:scorched_earth": "Leave nothing standing.",
    "synergy:pyromancer": "Some men just want to watch the board burn.",
    "synergy:permafrost": "The cold never bothered them anyway.",
    "synergy:absolute_zero": "Colder than your ex's heart.",
    "synergy:pandemic": "Patient zero says hello.",
    "synergy:blight": "Spreads like gossip.",
    "synergy:martyrdom": "My death will not be in vain!",
    "synergy:undying_legion": "What is dead may never die.",
    "synergy:deaths_harvest": "Reap what you sow.",
    "synergy:iron_phalanx": "Shield wall! Hold the line!",
    "synergy:sacred_ground": "Holy buffs on holy ground.",
    "synergy:fortress_protocol": "Maximum defense engaged.",
    "synergy:war_machine": "Mechanical mayhem.",
    "synergy:alpha_strike": "Hit first. Hit hardest.",
    "synergy:battle_hymn": "Music to kill by.",
    "synergy:midas_touch": "Everything turns to gold.",
    "synergy:trade_empire": "Buy low, sell... also low.",
    "synergy:entropy": "Order into chaos.",
    "synergy:madness": "Sanity is overrated.",
    "synergy:endless_horde": "They just keep coming.",
    "synergy:pack_hunters": "Alone we're strong. Together we're terrifying.",
    "synergy:elemental_fury": "Fire, ice, and poison walk into a bar.",
    "synergy:thermal_shock": "Hot and cold don't mix. Except here.",
    "synergy:master_forger": "Forged in the fires of obsession.",
    "synergy:phantom_army": "An army of ghosts.",
    "synergy:the_collection": "Gotta catch 'em all.",
    "synergy:blood_economy": "Blood is the new gold.",

    # ── Masters ───────────────────────────────────────────────────────
    "master:the_strategist": "Always five moves ahead.",
    "master:the_arsonist": "Some boards just want to burn.",
    "master:the_blacksmith": "Forge your destiny.",
    "master:the_gambler": "Lady Luck is a fickle mistress.",
    "master:the_necromancer": "Death is just the beginning.",
    "master:the_tactician": "Position is everything.",
    "master:the_pauper": "Less is more. Much more.",
    "master:the_collector": "One of everything, please.",
    "master:the_berserker": "RAAAAGH!",
    "master:the_warden": "Order on my board.",
    "master:the_alchemist": "Mix, match, explode.",
    "master:the_hivemind": "We are one. We are many.",
    "master:the_phantom": "Now you see me...",
    "master:the_merchant": "Everything's for sale.",
    "master:the_anarchist": "Rules? What rules?",
    "master:the_mirror_master": "Reflect. Adapt. Overcome.",

    # ── Achievements ──────────────────────────────────────────────────
    "achievement:first_blood": "Everyone starts somewhere.",
    "achievement:veteran": "Battle-hardened and tournament-tested.",
    "achievement:warlord": "Born to conquer.",
    "achievement:endurance": "Persistence is key.",
    "achievement:hoarder": "Gold! Gold everywhere!",
    "achievement:mogul": "The Scrooge McDuck of chess.",
    "achievement:boss_slayer": "Big game hunter.",
    "achievement:executioner_ach": "No boss is safe.",
    "achievement:clutch": "Living on the edge. Literally.",
    "achievement:perfectionist": "Grandmaster of grandmasters.",
    "achievement:heavy_hitter": "That's gonna leave a mark.",
    "achievement:army_builder": "The more the merrier.",
    "achievement:last_stand": "One piece to rule them all.",
    "achievement:untouchable": "Didn't even scratch the paint.",
    "achievement:overkill": "Was that really necessary? Yes.",
    "achievement:blitz": "Speed kills.",
    "achievement:combo_master": "Chain reaction!",
    "achievement:elemental": "Captain Planet, eat your heart out.",
    "achievement:assassins_creed": "Triple kill!",
    "achievement:necromancy": "They just won't stay dead.",
    "achievement:penny_pincher": "Save it for a rainy day.",
    "achievement:bargain_hunter": "I'd like to speak to the shop manager.",
    "achievement:collector": "Artifact hoarder extraordinaire.",
    "achievement:bibliophile": "So many cards, so little deck space.",
    "achievement:recycler": "Reduce, reuse, resell.",
    "achievement:investor": "Stimulating the economy.",
    "achievement:golden_age": "Swimming in gold.",
    "achievement:war_profiteer": "War is good for business.",
    "achievement:synergist": "The power of teamwork.",
    "achievement:scholar": "Knowledge is power.",
    "achievement:encyclopedia": "I know everything. EVERYTHING.",
    "achievement:variety_pack": "Variety is the spice of chess.",
    "achievement:mad_scientist": "What could possibly go wrong?",
    "achievement:alchemist": "Tarot connoisseur.",
    "achievement:curator": "A fine addition to my collection.",
    "achievement:strategist": "Jack of all masters.",
    "achievement:completionist": "Master of masters.",
    "achievement:all_seeing": "The codex completionist.",
    "achievement:pacifist": "Violence isn't always the answer.",
    "achievement:pawn_star": "Best I can do is pawns.",
    "achievement:chaos_run": "Embrace the chaos.",
    "achievement:speedrunner": "Any% tournament WR.",
    "achievement:deathless": "Not a scratch.",
    "achievement:minimalist": "Less is more, even in war.",
    "achievement:ironman": "No shop, no problem.",
    "achievement:true_master": "Every boss, beaten.",
    "achievement:lucky_7": "The stars aligned. All seven of them.",
    "achievement:mirror_match": "Spider-Man pointing meme.",
    "achievement:phoenix_down": "It keeps getting back up!",
    "achievement:domination": "Total. Board. Control.",
    "achievement:ouroboros": "The serpent eats its tail.",
}
